# ---------------------------------------------------------
# Configuration file for http://travis-ci.org/#!/karmi/tire
# ---------------------------------------------------------

script: "bundle exec rake test:unit"

rvm:
  - 1.8.6
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - ree
  - rbx-2.0
  - jruby

notifications:
  disable: true
